# Generated by Django 4.2.18 on 2025-01-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('hometown', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200, null=True)),
                ('brother_name', models.CharField(max_length=200, null=True)),
                ('rush_semester', models.CharField(max_length=200, null=True)),
                ('rush_year', models.CharField(max_length=200, null=True)),
                ('membership_status', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
