# Generated by Django 4.2.18 on 2025-01-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='membership_status',
            field=models.CharField(choices=[('New Member', 'New Member'), ('Active', 'Active'), ('Alumni', 'Alumni')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='rush_semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=200, null=True),
        ),
    ]
