# Generated by Django 4.2.18 on 2025-01-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_brother_membership_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='membership_status',
            field=models.CharField(choices=[('New Member', 'New Member'), ('Active', 'Active'), ('Active Exec', 'Active Exec'), ('Alumni', 'Alumni'), ('Alumni Exec', 'Alumni Exec')], max_length=200, null=True),
        ),
    ]
