# Generated by Django 4.2.18 on 2025-01-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_brother_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='grad_semester',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brother',
            name='grad_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='birthday',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='hometown',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='major',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brother',
            name='rush_semester',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='rush_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
