# Generated by Django 4.2.18 on 2025-01-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_brother_grad_semester_brother_grad_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_status', models.CharField(choices=[('New Member', 'New Member'), ('Active', 'Active'), ('Active Exec', 'Active Exec'), ('Alumni', 'Alumni'), ('Alumni Exec', 'Alumni Exec')], max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='brother',
            name='membership_status',
        ),
        migrations.CreateModel(
            name='Dashboard_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('redirect', models.CharField(max_length=200, null=True)),
                ('membership_status', models.ManyToManyField(to='accounts.membership_status')),
            ],
        ),
        migrations.AddField(
            model_name='brother',
            name='membership_status',
            field=models.ManyToManyField(to='accounts.membership_status'),
        ),
    ]
