# Generated by Django 4.2.18 on 2025-01-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membership_status_remove_brother_membership_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership_status',
            name='membership_status',
        ),
    ]
