# Generated by Django 4.2.18 on 2025-01-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_brother_membership_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard_link',
            old_name='name',
            new_name='dashboard_redirect_name',
        ),
    ]
