# Generated by Django 4.2.18 on 2025-01-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_name_dashboard_link_dashboard_redirect_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='membership_status',
            field=models.CharField(choices=[('New Member', 'New Member'), ('Active', 'Active'), ('Active Exec', 'Active Exec'), ('Pledge Board', 'Pledge Board'), ('Alumni', 'Alumni'), ('Alumni Exec', 'Alumni Exec')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard_link',
            name='membership_status',
            field=models.CharField(choices=[('New Member', 'New Member'), ('Active', 'Active'), ('Active Exec', 'Active Exec'), ('Pledge Board', 'Pledge Board'), ('Alumni', 'Alumni'), ('Alumni Exec', 'Alumni Exec')], max_length=200, null=True),
        ),
    ]
